const CATEGORY_FILTER_CONFIG_TYPES = {
  CHECKBOX: 'CHECKBOX',
  ONE_FROM_LIST: 'ONE_FROM_LIST',
  REVIEW: 'REVIEW',
  PRICE: 'PRICE',
  BRAND: 'BRAND',
  ONE_FROM_LIST: 'ONE_FROM_LIST'
}

export default CATEGORY_FILTER_CONFIG_TYPES
